### ISSUE TITLE
Use Pytables for storing wordvecspace data

### ISSUE THREAD

**Issue by RamanjaneyuluIdavalapati** [deep-compute/wordvecspace#21]

**Comment by RamanjaneyuluIdavalapati** [comment]
- Some of the links to refer
https://deepcompute.facebook.com/groups/1829047344033023/permalink/1986571074947315/
https://kastnerkyle.github.io/posts/using-pytables-for-larger-than-ram-data-processing/

**Comment by prashanthellina** [comment]
@RamanjaneyuluIdavalapati We need to capture in this issue why we are choosing to change to HDF5 from Numpy format. @chatrapathik Please post notes on the proposed structure within the HDF5 file.

**Comment by chatrapathik** [comment]
Sure @prashanthellina.

**Comment by chatrapathik** [comment]
@prashanthellina @RamanjaneyuluIdavalapati @prasannababuAddagiri The proposed structure of the HDF5 file is like below.
- HDF5 file acts like a database. Here each array is one table. In tables, we are storing our data.
- The HDF5 file contains 3 Earray to store vectors, words, occurrences.
![27016644_171614553601582_715388560_o 1](https://user-images.githubusercontent.com/23492860/35137657-908e5a44-fd10-11e7-94db-82a949f92b30.jpg)

Note:
**Reason behind switching from Numpy format to HDF5**.
- If we use numpy to load data, it will load the entire data in the ram. If the file size is very large it will consume whole of the ram.
- To overcome this problem we are using the HDF5 file to store data. Because HDF5 uses the disk space. It won't consumes the ram.

**Comment by prashanthellina** [comment]
@RamanjaneyuluIdavalapati  @chatrapathik We will also have to update the `convert` subcommand to convert from Google's format to the new one. While doing this, let us write code to load word occurrences data as well.

**Comment by RamanjaneyuluIdavalapati** [comment]
@prashanthellina 
Can we close this issue?

**Comment by prashanthellina** [comment]
Yes please
